package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    try {
      flutterEngine.getPlugins().add(new pl.pszklarska.beaconbroadcast.BeaconBroadcastPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin beacon_broadcast, pl.pszklarska.beaconbroadcast.BeaconBroadcastPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new it.thoson.device_uuid.DeviceUuidPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin device_uuid, it.thoson.device_uuid.DeviceUuidPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new de.gigadroid.flutter_udid.FlutterUdidPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin flutter_udid, de.gigadroid.flutter_udid.FlutterUdidPlugin", e);
    }
  }
}
